# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0015_auto_20170207_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(choices=[(2017, '2016/2017')], verbose_name='Saison')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lieu')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('representative', models.CharField(blank=True, max_length=100, verbose_name="Représentant de l'échelon régional/national")),
                ('headcount', models.IntegerField(blank=True, null=True, verbose_name='Effectif présents')),
                ('voters', models.IntegerField(blank=True, null=True, verbose_name='Nombre de votants')),
                ('favour', models.IntegerField(blank=True, null=True, verbose_name='Pour')),
                ('against', models.IntegerField(blank=True, null=True, verbose_name='Contre')),
                ('absention', models.IntegerField(blank=True, null=True, verbose_name='Abstention')),
                ('result', models.IntegerField(blank=True, null=True, verbose_name="Résultat de l'exercice en cours")),
                ('budget', models.NullBooleanField(verbose_name="Présentation d'un budget prévisionnel")),
                ('delegate_votes', models.IntegerField(blank=True, null=True, verbose_name='Voix obtenues')),
                ('alternate_votes', models.IntegerField(blank=True, null=True, verbose_name='Voix obtenues')),
                ('leader_votes', models.IntegerField(blank=True, null=True, verbose_name='Voix obtenues')),
                ('treasurer_votes', models.IntegerField(blank=True, null=True, verbose_name='Voix obtenues')),
                ('activity_comments', models.TextField(blank=True, verbose_name="Commentaires concernant le temps rapport d'activité")),
                ('financial_comments', models.TextField(blank=True, verbose_name='Commentaires concernant le point financier')),
                ('national_comments', models.TextField(blank=True, verbose_name='Commentaires concernant les sujets d’intérêts nationaux abordés')),
                ('regional_comments', models.TextField(blank=True, verbose_name='Commentaires concernant les sujets d’intérêts régionaux abordés')),
                ('problems', models.TextField(blank=True, verbose_name='Problèmes/difficultés survenus dans la tenue de la réunion')),
                ('scan', models.FileField(blank=True, upload_to='', verbose_name='Scan du PV papier')),
                ('alternate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternate_set', to=settings.AUTH_USER_MODEL, verbose_name='Délégué suppléant élu')),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegate_set', to=settings.AUTH_USER_MODEL, verbose_name='Délégué élu')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_set', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Structure', verbose_name='Structure')),
                ('treasurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_set', to=settings.AUTH_USER_MODEL, verbose_name='Trésorier')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membre')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.Report')),
            ],
        ),
    ]
