# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20170117_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingstate',
            options={'ordering': ('title',), 'verbose_name': 'Statut'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='org_type',
            field=models.IntegerField(blank=True, choices=[(1, 'EEDF'), (2, 'Scouts français'), (3, 'Scouts étrangers'), (4, 'Association'), (5, 'Particulier'), (6, 'Scolaires')], null=True, verbose_name="Type d'organisation"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.BookingState', verbose_name='Statut'),
        ),
    ]
