# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20170118_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='file',
        ),
        migrations.AddField(
            model_name='agreement',
            name='odt',
            field=models.FileField(blank=True, upload_to='conventions'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='pdf',
            field=models.FileField(blank=True, upload_to='conventions'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='order',
            field=models.IntegerField(verbose_name="Numéro d'ordre"),
        ),
    ]
