# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20170118_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.IntegerField(choices=[(1, 'Chèque'), (2, 'Virement'), (3, 'Espèces')], verbose_name='Moyen de paiement')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.Booking')),
            ],
        ),
    ]
