# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstate',
            name='income',
            field=models.IntegerField(choices=[(1, 'Potentiel'), (2, 'Confirmé'), (3, 'Facturé'), (4, 'Infirmé'), (5, 'Annulé')], default=1, verbose_name="Chiffre d'affaire"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(),
        ),
    ]
