# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20170119_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstate',
            name='color',
            field=models.CharField(choices=[('default', 'Gris'), ('primary', 'Bleu'), ('success', 'Vert'), ('info', 'Cyan'), ('warning', 'Orange'), ('danger', 'Rouge')], default='default', max_length=10, verbose_name='Couleur'),
            preserve_default=False,
        ),
    ]
