# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Booking = apps.get_model("booking", "Booking")
    for booking in Booking.objects.exclude(signed_agreement=None):
        booking.signed_agreement.booking = booking
        booking.signed_agreement.save()
        booking.signed_agreement = None
        booking.save()


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_bookingstate_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='agreement',
            new_name='signed_agreement',
        ),
        migrations.AlterField(
            model_name='booking',
            name='signed_agreement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_booking', to='booking.Agreement', verbose_name='Convention signée'),
        ),
        migrations.AddField(
            model_name='booking',
            name='signed_agreement_scan',
            field=models.FileField(blank=True, upload_to='conventions_signees'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='booking.Booking', verbose_name='Réservation'),
        ),
        migrations.RunPython(forwards_func),
    ]
