# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20170127_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice',
            field=models.FileField(blank=True, upload_to='factures', verbose_name='Facture'),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
