# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20170223_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'get_latest_by': 'date', 'ordering': ('order',), 'verbose_name': 'Convention'},
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_scan',
            field=models.FileField(blank=True, upload_to='assurance', verbose_name="Attestation d'assurance"),
        ),
    ]
