# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_structure_google'),
        ('booking', '0014_auto_20170226_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='structure',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='members.Structure', verbose_name='Structure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='structure',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='members.Structure', verbose_name='Structure'),
            preserve_default=False,
        ),
    ]
