# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import members.utils


def set_year(apps, schema_editor):
    Booking = apps.get_model('booking', 'Booking')
    for booking in Booking.objects.all():
        item = booking.items.first()
        if item and item.begin:
            booking.year = item.begin.year
            booking.save()


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20170305_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='year',
            field=models.IntegerField(default=members.utils.current_year, verbose_name='Année'),
        ),
        migrations.RunPython(set_year, migrations.RunPython.noop),
    ]
