# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_booking_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-year', 'title'), 'permissions': (('show_booking', 'Can show booking'),), 'verbose_name': 'Réservation'},
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_place',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Placement souhaité'),
        ),
        migrations.AddField(
            model_name='booking',
            name='wood',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Bois'),
        ),
    ]
