# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-23 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20180225_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mean',
            field=models.IntegerField(choices=[(1, 'Chèque'), (2, 'Virement'), (3, 'Espèces'), (4, 'ANCV')], verbose_name='Moyen de paiement'),
        ),
    ]
