# Generated by Django 2.1.7 on 2019-02-13 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20180923_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='booking.Booking', verbose_name='Réservation'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Structure', verbose_name='Structure'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='signed_agreement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signedx_booking', to='booking.Agreement', verbose_name='N° convention signée'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.BookingState', verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Structure', verbose_name='Structure'),
        ),
        migrations.AlterField(
            model_name='trackingvalue',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.TrackingEvent', verbose_name='Événement'),
        ),
    ]
