# Generated by Django 2.1.7 on 2019-03-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20190213_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='structure',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='booking.Booking', verbose_name='Réservation'),
        ),
    ]
