# Generated by Django 2.1.7 on 2019-07-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20190317_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mean',
            field=models.IntegerField(choices=[(1, 'Chèque'), (2, 'Virement'), (3, 'Espèces'), (4, 'ANCV'), (5, 'CB')], verbose_name='Moyen de paiement'),
        ),
    ]
