# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invoice',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
