# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becours', '0002_group_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='begin',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='comfort',
            field=models.IntegerField(choices=[(1, 'Terrain'), (2, 'Village'), (3, 'Mixte')], editable=False, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='end',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='nights',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='number',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='overnights',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
