# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becours', '0003_auto_20161013_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='state',
            field=models.IntegerField(choices=[(1, 'Demande de renseignements'), (2, 'Demande de devis'), (3, 'Devis établi'), (4, 'Devis signé'), (5, 'Facture établie'), (6, 'Facture payée')], default=1),
        ),
    ]
