# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becours', '0004_auto_20161023_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='estimate',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='state',
            field=models.IntegerField(choices=[(1, 'Demande de renseignements'), (2, 'Demande de devis'), (3, 'Devis établi'), (4, 'Devis signé'), (5, 'Facture établie'), (6, 'Facture payée'), (7, 'Annulé')], default=1),
        ),
    ]
