# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becours', '0005_auto_20161023_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='additional_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='coop_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='hosting_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='headcount',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
