# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becours', '0006_auto_20161105_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
