# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becours', '0007_group_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='headcount',
            name='hosting_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='headcount',
            name='overnights',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
