# Generated by Django 2.2.6 on 2019-10-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upkeep', '0002_auto_20191019_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='_issue_blocks_+', to='upkeep.Issue', verbose_name='Bloque'),
        ),
    ]
