# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20161008_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.IntegerField(choices=[(1, 'Cercle'), (2, 'Clan Ainé'), (3, 'Comité directeur'), (4, 'Département'), (5, 'Pôle'), (6, 'Région'), (7, 'Ronde'), (8, 'Siège'), (9, 'Sommet'), (10, "Structure locale d'activité"), (11, 'Structure locale rattachée'), (12, 'Unité Défi'), (13, 'Unité Eclé'), (14, 'Unité Nomade'), (15, 'Centre permanent national')], verbose_name='Type'),
        ),
    ]
