# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20170207_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Jeune/Participant'), (1, 'Responsable'), (2, 'Cadre bénévole'), (3, 'Stagiaire'), (4, 'Parent/Ami'), (5, 'Salarié/SC')], null=True, verbose_name='Categorie'),
        ),
    ]
