# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20170223_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Adhesion', verbose_name='Adhésion')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Function', verbose_name='Fonction')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Structure', verbose_name='Structure')),
                ('main', models.BooleanField(default=False, verbose_name='Principale'))
            ],
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together=set([('adhesion', 'structure', 'function')]),
        ),
    ]
