# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 08:55
from __future__ import unicode_literals

from django.db import migrations
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20170223_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='google',
            field=oauth2client.contrib.django_util.models.CredentialsField(null=True),
        ),
    ]
