# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20170305_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhesion',
            name='function',
        ),
    ]
