# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 15:38
from __future__ import unicode_literals

from django.db import migrations
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_remove_adhesion_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='google',
            field=oauth2client.contrib.django_util.models.CredentialsField(null=True, blank=True),
        ),
    ]
