# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_structure_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
    ]
