# Generated by Django 2.1.2 on 2018-10-05 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_person_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Rate', verbose_name='Tarif'),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adherents', to='members.Structure', verbose_name='Structure'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='adhesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Adhesion', verbose_name='Adhésion'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Function', verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Structure', verbose_name='Structure'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='members.Structure'),
        ),
    ]
