# Generated by Django 2.1.7 on 2019-03-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20190213_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='adhesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='members.Adhesion', verbose_name='Adhésion'),
        ),
    ]
