# Generated by Django 2.2.8 on 2020-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20190317_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='subtype',
            field=models.IntegerField(blank=True, choices=[(1, 'Centre et terrain'), (2, 'Groupe local')], null=True, verbose_name='Sous-type'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.IntegerField(choices=[(1, 'Cercle'), (2, 'Clan Ainé'), (3, 'Comité directeur'), (4, 'Département'), (5, 'Pôle'), (6, 'Région'), (7, 'Ronde'), (8, 'Siège'), (9, 'Sommet'), (10, "Structure locale d'activité"), (11, 'Structure locale rattachée'), (12, 'Unité Défi'), (13, 'Unité Eclé'), (14, 'Unité Nomade'), (15, 'Centre permanent national'), (16, 'Service vacances')], verbose_name='Type'),
        ),
    ]
