# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('number',), 'verbose_name': 'Compte'},
        ),
        migrations.AlterModelOptions(
            name='analytic',
            options={'ordering': ('title',), 'verbose_name': 'Analytique'},
        ),
    ]
