# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20170207_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='amount',
        ),
    ]
