# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_entry_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scan', models.FileField(upload_to='')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Solde')),
            ],
            options={
                'verbose_name': 'Relevé de compte',
                'ordering': ('-date',),
                'verbose_name_plural': 'Relevés de compte',
            },
        ),
    ]
