# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_bankstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='scan',
            field=models.FileField(blank=True, upload_to='justificatif'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='scan',
            field=models.FileField(upload_to='releves'),
        ),
    ]
