# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    Entry = apps.get_model('accounting', 'Entry')
    Transaction = apps.get_model('accounting', 'Transaction')
    for entry in Entry.objects.all():
        Transaction.objects.create(entry=entry, account=entry.account, analytic=entry.analytic,
                                   revenue=entry.revenue, expense=entry.expense)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20170224_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Recette')),
                ('expense', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dépense')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account', verbose_name='Compte')),
                ('analytic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Analytic', verbose_name='Analytique')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Entry')),
            ],
        ),
        migrations.RunPython(forward),
    ]
