# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='analytic',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='revenue',
        ),
    ]
