# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20170625_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entered',
            field=models.BooleanField(default=False, verbose_name='Saisi dans la compta'),
        ),
        migrations.AddField(
            model_name='entry',
            name='forwarded',
            field=models.BooleanField(default=False, verbose_name='Envoyé à la compta'),
        ),
    ]
