# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20170625_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Dépense'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Recette'),
        ),
    ]
