# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20170626_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Intitulé'),
        ),
    ]
