# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_transaction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Débit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Crédit'),
        ),
    ]
