# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_auto_20170628_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro'),
        ),
    ]
