# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_bankstatement_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reconciliation',
            field=models.DateField(blank=True, null=True, verbose_name='Rapprochement'),
        ),
    ]
