# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_transaction_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='projected',
            field=models.BooleanField(default=False, verbose_name='Prévisionnel'),
        ),
    ]
