# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_entry_projected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='analytic',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
