# Generated by Django 2.1.2 on 2018-10-05 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_auto_20170917_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Account', verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='analytic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Analytic', verbose_name='Analytique'),
        ),
    ]
