# Generated by Django 2.1.7 on 2019-07-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_purchaseinvoice_thirdpartyaccount_transferorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Entry'),
        ),
    ]
