# Generated by Django 2.1.7 on 2019-08-11 19:15

from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_auto_20190716_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4, verbose_name='Numéro')),
                ('title', models.CharField(max_length=100, verbose_name='Intitulé')),
                ('iban', localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, use_nordea_extensions=False, verbose_name='IBAN')),
                ('bic', localflavor.generic.models.BICField(blank=True, max_length=11, verbose_name='BIC')),
                ('client_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro client')),
            ],
            options={
                'verbose_name': 'Tiers',
                'verbose_name_plural': 'Tiers',
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='thirdparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.ThirdParty', verbose_name='Tiers'),
        ),
    ]
