# Generated by Django 2.1.7 on 2019-08-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_auto_20190811_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdpartyaccount',
            name='account_ptr',
        ),
        migrations.DeleteModel(
            name='ThirdPartyAccount',
        ),
    ]
