# Generated by Django 2.1.7 on 2019-08-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_auto_20190811_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytic',
            options={'ordering': ('number',), 'verbose_name': 'Analytique'},
        ),
        migrations.AddField(
            model_name='analytic',
            name='number',
            field=models.CharField(default='', max_length=3, verbose_name='Numéro'),
            preserve_default=False,
        ),
    ]
