# Generated by Django 2.1.7 on 2019-08-14 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_auto_20190812_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2, verbose_name='Numéro')),
                ('title', models.CharField(max_length=100, verbose_name='Intitulé')),
            ],
            options={
                'verbose_name': 'Journal',
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Journal', verbose_name='Journal'),
        ),
    ]
