# Generated by Django 2.1.7 on 2019-08-14 06:43

from django.db import migrations


def set_journal(apps, schema_editor):
    Entry = apps.get_model('accounting', 'Entry')
    Journal = apps.get_model('accounting', 'Journal')
    an = Journal.objects.create(number='AN', title="À nouveaux")
    bq = Journal.objects.create(number='BQ', title="Banque")
    ca = Journal.objects.create(number='CA', title="Caisse")
    ha = Journal.objects.create(number='HA', title="Achats")
    od = Journal.objects.create(number='OD', title="Opérations diverses")
    vt = Journal.objects.create(number='VT', title="Ventes")
    Entry.objects.filter(transaction__account__number__startswith='6').update(journal=ha)
    Entry.objects.filter(transaction__account__number__startswith='7').update(journal=vt)
    Entry.objects.filter(transaction__account__number__startswith='530').update(journal=ca)
    Entry.objects.filter(transaction__account__number__startswith='512').update(journal=bq)
    Entry.objects.filter(transaction__account__number__startswith='1').update(journal=an)
    Entry.objects.filter(journal=None).update(journal=od)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_auto_20190814_0843'),
    ]

    operations = [
        migrations.RunPython(set_journal, migrations.RunPython.noop),
    ]
