# Generated by Django 2.1.7 on 2019-08-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_auto_20190818_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=7, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='number',
            field=models.CharField(max_length=3, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='number',
            field=models.CharField(max_length=2, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='number',
            field=models.CharField(max_length=4, unique=True, verbose_name='Numéro'),
        ),
    ]
