# Generated by Django 2.1.7 on 2019-09-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_auto_20190819_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferorder',
            name='xml',
        ),
    ]
