# Generated by Django 2.1.7 on 2019-09-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_remove_transferorder_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='type',
            field=models.IntegerField(choices=[(0, 'Client'), (1, 'Fournisseur'), (2, 'Salarié'), (3, 'Autre')], default=0, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
