# Generated by Django 2.1.7 on 2019-10-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_auto_20190908_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='projected',
        ),
    ]
