# Generated by Django 2.1.7 on 2019-10-06 11:45

from django.db import migrations


def remove_projected(apps, schema_editor):
    Entry = apps.get_model('accounting', 'Entry')
    Entry.objects.filter(projected=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_remove_entry_projected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='projected',
        ),
    ]
