# Generated by Django 2.1.7 on 2019-10-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_remove_entry_forwarded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entered',
            new_name='exported',
        ),
    ]
