# Generated by Django 2.1.7 on 2019-10-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_auto_20191006_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='exported',
            field=models.BooleanField(default=False, verbose_name='Exporté'),
        ),
    ]
