# Generated by Django 2.1.7 on 2019-10-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_auto_20191006_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Intitulé')),
                ('start', models.DateField(verbose_name='Début')),
                ('end', models.DateField(verbose_name='Fin')),
            ],
            options={
                'verbose_name': 'Exercice',
                'ordering': ('start', 'end'),
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Year', verbose_name='Exercice'),
        ),
    ]
