# Generated by Django 2.1.7 on 2019-10-12 11:33

from datetime import date
from django.db import migrations


def set_year(apps, schema_editor):
    Entry = apps.get_model('accounting', 'entry') 
    Year = apps.get_model('accounting', 'year')
    titles = Entry.objects.values_list('date__year', flat=True).distinct()
    for title in sorted(titles):
        year = Year.objects.create(
            title=title,
            start=date(title, 1, 1),
            end=date(title, 12, 31),
        )
        Entry.objects.filter(date__year=title).update(year=year)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_auto_20191012_1336'),
    ]

    operations = [
        migrations.RunPython(set_year, migrations.RunPython.noop)
    ]
