# Generated by Django 2.1.7 on 2019-10-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_auto_20191012_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Year', verbose_name='Exercice'),
        ),
    ]
