# Generated by Django 2.1.7 on 2019-10-12 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_auto_20191012_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Year', verbose_name='Exercice'),
        ),
    ]
