# Generated by Django 2.1.7 on 2019-10-12 12:53

from django.db import migrations


def set_year(apps, schema_editor):
    BankStatement = apps.get_model('accounting', 'BankStatement') 
    Year = apps.get_model('accounting', 'Year')
    titles = BankStatement.objects.values_list('date__year', flat=True).distinct()
    for title in sorted(titles):
        year = Year.objects.get(title=title)
        BankStatement.objects.filter(date__year=title).update(year=year)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_bankstatement_year'),
    ]

    operations = [
        migrations.RunPython(set_year, migrations.RunPython.noop)
    ]
