# Generated by Django 2.1.7 on 2019-10-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_auto_20191012_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.Entry')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Numéro')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
            },
            bases=('accounting.entry',),
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Achat', 'verbose_name_plural': 'Achats'},
        ),
    ]
