# Generated by Django 2.2.8 on 2019-12-08 19:50

from django.db import migrations


def set_expenditure_method(apps, schema_editor):
    Expenditure = apps.get_model('accounting', 'Expenditure')
    Expenditure.objects.filter(title__icontains='cb').update(method=1)
    Expenditure.objects.filter(title__icontains='chèque').update(method=2)
    Expenditure.objects.filter(transaction__account__number='5300000').update(method=3)
    Expenditure.objects.filter(title__icontains='prélèvement').update(method=4)
    Expenditure.objects.filter(title__icontains='virement').update(method=5)
    for expenditure in Expenditure.objects.filter(method=0):
        print("WARNING! Expenditure #{} {} has no paiement method".format(expenditure.id, expenditure.title))


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0056_expenditure_method'),
    ]

    operations = [
        migrations.RunPython(set_expenditure_method, migrations.RunPython.noop),
    ]
