# Generated by Django 2.2.8 on 2019-12-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0057_auto_20191208_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferOrder',
        ),
    ]
