# Generated by Django 2.2.8 on 2020-01-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_delete_transferorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='opened',
            field=models.BooleanField(default=False, verbose_name='Ouvert'),
        ),
    ]
