# Generated by Django 2.2.13 on 2020-12-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_year_opened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashing',
            options={'verbose_name': 'Remise', 'verbose_name_plural': 'Remises'},
        ),
    ]
