# Generated by Django 2.2.13 on 2020-12-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0060_auto_20201221_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='method',
            field=models.IntegerField(choices=[(1, 'Carte bancaire'), (2, 'Chèque'), (3, 'Espèces'), (4, 'Prélèvement'), (5, 'Virement'), (6, 'Remboursement CB')]),
        ),
    ]
